# Makefile for macOS.
CXX := clang++
CXXFLAGS := -std=c++14 -Wall -Werror
PKG_CONFIG := pkg-config

MPV_CXXFLAGS := $(shell $(PKG_CONFIG) --cflags mpv)
MPV_LIBS := $(shell $(PKG_CONFIG) --libs mpv)

NCURSES_CXXFLAGS := $(shell $(PKG_CONFIG) --cflags ncurses)
NCURSES_LIBS := $(shell $(PKG_CONFIG) --libs ncurses)

FLUIDSYNTH_CXXFLAGS := $(shell $(PKG_CONFIG) --cflags fluidsynth)
FLUIDSYNTH_LIBS := $(shell $(PKG_CONFIG) --libs fluidsynth)

SRC_DIR := src
OBJ_DIR := obj
TARGET := nomp

# Find all cpp files recursively
SRCS := $(shell find $(SRC_DIR) -name '*.cpp')

# Map src/.../*.cpp to bin/.../*.o
OBJS := $(SRCS:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)

# Default target
all: $(TARGET)

# link
$(TARGET): $(OBJS)
	$(CXX) $(OBJS) -o $@ $(MPV_LIBS) $(NCURSES_LIBS)

# compile .cpp files into .o files
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(MPV_CXXFLAGS) $(NCURSES_CXXFLAGS) $(FLUIDSYNTH_CXXFLAGS)-c $< -o $@

# If running with clean argument,
# clean up object files and binary.
clean:
	rm -rf nomp $(OBJ_DIR)
